### ISSUE TITLE
Bot Crashed on an Action Command containing a Channel

### ISSUE THREAD

**Issue by dwhagar** [dwhagar/snowboard#63]
[16/09/17 19:34:43.882]  \* Thumper will probably not even be safe for upstairs, and will have to join #multiverse-attic

Traceback (most recent call last):
  File "snowboard.py", line 27, in <module>
    sys.exit(snowboard.main(sys.argv[1:]))
  File "/home/cyclops/snowboard/snowboard/main.py", line 255, in main
    cmds = __process_responses(net, data)
  File "/home/cyclops/snowboard/snowboard/main.py", line 122, in __process_responses
    cmds = __get_commands(raw, net)
  File "/home/cyclops/snowboard/snowboard/main.py", line 189, in __get_commands
    commands += scripts.rawMessages(net, raw)
  File "/home/cyclops/snowboard/snowboard/scripts.py", line 101, in rawMessages
    seenCommands.rawTriggers(net, message)
  File "/home/cyclops/snowboard/snowboard/seenCommands.py", line 95, in rawTriggers
    seen.save(nick, host, act)
UnboundLocalError: local variable 'act' referenced before assignment

**Comment by RodentOfUnusualSize** [comment]
The problem seems to have been caused by line 42 in `seenCommands.py`:

``` py
dbTriggerC = r"^(.*)!(.*@.*) (JOIN|PART) (#.*)$"
```

What's happening is that third `.*` is eating everything up until the `join` (because `*` is greedy).

So: `nick!user@host (whatever goes here) will probably not even be safe for upstairs, and will have to join #multiverse-attic` is being interpreted as:
-   `nick` as the first match;
-   `user@host (whatever goes here) will probably not even be safe for upstairs, and will have to` as the second match;
-   `join` as the third match; and
-   `#multiverse-attic` as the fourth match.

_THEN_ what happens is the 3rd match is `join`... not `JOIN`. so on lines 90-93:

``` py
        if data[3] == "JOIN":
            act = "joining " + dest
        elif data[3] == "PART":
            act = "leaving " + dest
```

Nothing gets matched (because `join` != `JOIN`).

Thus `act` never gets set. Thus you get the unbound local error.

**Comment by RodentOfUnusualSize** [comment]
The ideal fix would probably to make more restrictive regexes. That is, not `.*`, but rather `[a-zA-Z0-9-_.]+` (assuming that character range is suitable for a nick, user, or host). Or perhaps instead of `(.*)!(.*@.*) (JOIN|PART) (#.*)` use `([^!]+)!([^@]+)@([^ ]+) (JOIN|PART) (#.*)`.

**Comment by dwhagar** [comment]
I just stopped using Regular Expressions altogether.  Easier that way.
